[app]
# Interface and port where the app will run its webserver.
address = "0.0.0.0:9000"

# Database.
[db]
host = "db4"
port = 5432
user = "listmonk4"
password = "listmonk4"
database = "listmonk4"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
